using Microsoft.CodeAnalysis;
using System;
using System.Linq;
using System.Text;

// Generated by Claude Sonnet 5 Medium
// (because I'm a lazy ass)
namespace Generators.Ecs
{
    [Generator]
    public class QueryGenerator : ISourceGenerator
    {
        private const int MinArity = 1;
        private const int MaxArity = 16;

        public void Execute(GeneratorExecutionContext context)
        {
            for (int arity = MinArity; arity <= MaxArity; arity++)
            {
                string source = GenerateSource(arity);
                context.AddSource($"Query{arity}.g.cs", source);
            }
        }

        public void Initialize(GeneratorInitializationContext context){}

        private static string GenerateSource(int arity)
        {
            var typeParams = Enumerable.Range(1, arity).Select(i => $"T{i}").ToArray();

            string typeParamList = string.Join(", ", typeParams);
            string constraints = string.Join(" ", typeParams.Select(t => $"where {t} : struct, IComponent"));
            string refParams = string.Join(", ", typeParams.Select((t, idx) => $"ref {t} t{idx + 1}"));

            // A 1-element ValueTuple can't be written with tuple literal/type syntax in C#,
            // so arity 1 falls back to the plain (non-tuple) column type, same shape the
            // hand-written class would need if it only tracked a single component.
            string cachedColumnsType = arity == 1
                ? "Column<T1>"
                : $"({string.Join(", ", typeParams.Select((t, idx) => $"Column<{t}> Column{idx + 1}"))})";

            string getColumnsExpr = arity == 1
                ? "archetype.GetColumn<T1>()"
                : $"({string.Join(", ", typeParams.Select(t => $"archetype.GetColumn<{t}>()"))})";

            string deconstructPattern = arity == 1
                ? "col1"
                : $"({string.Join(", ", Enumerable.Range(1, arity).Select(i => $"col{i}"))})";

            string actionArgs = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"ref col{i}[i]"));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Enjune.Ecs.Component;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace Enjune.Ecs.EcsType;");
            sb.AppendLine();
            sb.AppendLine($"public delegate void ForEachRef<{typeParamList}>({refParams}) {constraints};");
            sb.AppendLine();
            sb.AppendLine($"public sealed class Query<{typeParamList}>(World world, Signature include, Signature exclude) {constraints}");
            sb.AppendLine("{");
            sb.AppendLine("    private readonly World _world = world;");
            sb.AppendLine("    private readonly Signature _include = include;");
            sb.AppendLine("    private readonly Signature _exclude = exclude;");
            sb.AppendLine();
            sb.AppendLine("    private readonly List<Archetype> _cachedArchetypes = [];");
            sb.AppendLine($"    private readonly List<{cachedColumnsType}> _cachedColumns = [];");
            sb.AppendLine("    private int _cacheVersion = 0;");
            sb.AppendLine();
            sb.AppendLine();
            sb.AppendLine("    private void ValidateCache()");
            sb.AppendLine("    {");
            sb.AppendLine("        if (_world.CacheVersion != _cacheVersion)");
            sb.AppendLine("            return;");
            sb.AppendLine("        _cacheVersion = _world.CacheVersion;");
            sb.AppendLine("        _cachedArchetypes.Clear();");
            sb.AppendLine("        foreach (var archetype in _world.QueryArchetypes(_include, _exclude))");
            sb.AppendLine("        {");
            sb.AppendLine("            _cachedArchetypes.Add(archetype);");
            sb.AppendLine($"            _cachedColumns.Add({getColumnsExpr});");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    public void ForEach(ForEachRef<{typeParamList}> action)");
            sb.AppendLine("    {");
            sb.AppendLine("        ValidateCache();");
            sb.AppendLine($"        foreach (var {deconstructPattern} in _cachedColumns)");
            sb.AppendLine("        {");
            sb.AppendLine("            for (int i = 0; i < col1.Count; i++)");
            sb.AppendLine("            {");
            sb.AppendLine($"                action({actionArgs});");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
