using Microsoft.CodeAnalysis;
using System;
using System.Data;
using System.Linq;
using System.Text;

namespace Generators.Ecs
{
    [Generator]
    public class QueryGenerator : ISourceGenerator
    {
        private const int MinArity = 1;
        private const int MaxArity = 16;

        public void Execute(GeneratorExecutionContext context)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Enjune.Ecs.Component;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace Enjune.Ecs.EcsType;");

            // Add all delegate versions
            AddDelegateSeries(sb);

            sb.AppendLine($"public partial class Query");
            sb.AppendLine("{");

            // Add all ForEach method versions
            AddForEachMethodSeries(sb);

            // Add all nested Cache classes
            AddNestedCacheSeries(sb);

            sb.AppendLine("}");

            var source = sb.ToString();
            context.AddSource($"Query.g.cs", source);
        }

        public void Initialize(GeneratorInitializationContext context) { }

        private static void AddDelegate(StringBuilder sb, int arity)
        {
            var typeParams = Enumerable.Range(1, arity).Select(i => $"T{i}").ToArray();
            string typeParamList = string.Join(", ", typeParams);
            string constraints = string.Join(" ", typeParams.Select(t => $"where {t} : struct, IComponent"));
            string refParams = string.Join(", ", typeParams.Select((t, idx) => $"ref {t} t{idx + 1}"));

            sb.AppendLine($"public delegate void ForEachDelegate<{typeParamList}>(Entity entity, {refParams}) {constraints};");
        }

        private static void AddDelegateSeries(StringBuilder sb)
        {
            for (int arity = MinArity; arity <= MaxArity; arity++) AddDelegate(sb, arity);
        }

        private static void AddForEachMethod(StringBuilder sb, int arity)
        {
            var typeParams = Enumerable.Range(1, arity).Select(i => $"T{i}").ToArray();
            string typeParamList = string.Join(", ", typeParams);
            string constraints = string.Join(" ", typeParams.Select(t => $"where {t} : struct, IComponent"));

            string deconstructPattern = $"(entities, {string.Join(", ", Enumerable.Range(1, arity).Select(i => $"col{i}"))})";
            string actionArgs = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"ref col{i}[i]"));

            sb.AppendLine($"    public void ForEach<{typeParamList}>(ForEachDelegate<{typeParamList}> action) {constraints}");
            sb.AppendLine("    {");
            sb.AppendLine($"        var cache = Cache<{typeParamList}>.GetCache(_world, _include, _exclude);");
            sb.AppendLine($"        foreach (var {deconstructPattern} in cache)");
            sb.AppendLine("        {");
            sb.AppendLine("            for (int i = 0; i < col1.Count; i++)");
            sb.AppendLine("            {");
            sb.AppendLine($"                    action(entities[i], {actionArgs});");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        private static void AddForEachMethodSeries(StringBuilder sb)
        {
            for (int arity = MinArity; arity <= MaxArity; arity++) AddForEachMethod(sb, arity);
        }

        private static void AddNestedCache(StringBuilder sb, int arity)
        {
            var typeParams = Enumerable.Range(1, arity).Select(i => $"T{i}").ToArray();
            string typeParamList = string.Join(", ", typeParams);
            string constraints = string.Join(" ", typeParams.Select(t => $"where {t} : struct, IComponent"));
            string cacheType = $"(Entity[] entities, {string.Join(", ", typeParams.Select((t, idx) => $"Column<{t}> Column{idx + 1}"))})";
            string getColumnsExpr = $"(archetype.GetEntities(), {string.Join(", ", typeParams.Select(t => $"archetype.GetColumn<{t}>()"))})";

            sb.AppendLine($"    private static class Cache<{typeParamList}> {constraints}");
            sb.AppendLine("    {");
            sb.AppendLine($"        private static List<{cacheType}> _cache = [];");
            sb.AppendLine($"        private static int _cacheVersion = -1;");
            sb.AppendLine($"        internal static List<{cacheType}> GetCache(");
            sb.AppendLine( "            World world, Signature include, Signature exclude)");
            sb.AppendLine( "        {");
            sb.AppendLine("            if (world.CacheVersion == _cacheVersion) return _cache;");
            sb.AppendLine("            _cache.Clear();");
            sb.AppendLine("            foreach (var archetype in world.QueryArchetypes(include, exclude))");
            sb.AppendLine("            {");
            sb.AppendLine($"                _cache.Add({getColumnsExpr});");
            sb.AppendLine("            }");
            sb.AppendLine("            _cacheVersion = world.CacheVersion;");
            sb.AppendLine("            return _cache;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        private static void AddNestedCacheSeries(StringBuilder sb)
        {
            for (int arity = MinArity; arity <= MaxArity; arity++) AddNestedCache(sb, arity);
        }
    }
}
