using Microsoft.CodeAnalysis;
using System;
using System.Data;
using System.Linq;
using System.Text;

namespace Generators.Ecs
{
    [Generator]
    public class QueryGenerator : ISourceGenerator
    {
        private const int MinArity = 1;
        private const int MaxArity = 8;

        public void Execute(GeneratorExecutionContext context)
        {
            var sb = new StringBuilder();
            sb.AppendLine(@"// <auto-generated/>");
            sb.AppendLine(@"using Enjune.Ecs.Component;");
            sb.AppendLine(@"using System.Collections.Generic;");
            sb.AppendLine(@"");
            sb.AppendLine(@"namespace Enjune.Ecs.EcsType;");

            // Add all delegate versions
            AddDelegateSeries(sb);

            // Add all Query<> versions
            AddQueryClassSeries(sb);

            var source = sb.ToString();
            context.AddSource($"Query.g.cs", source);

            sb = new StringBuilder();
            sb.AppendLine(@"// <auto-generated/>");
            sb.AppendLine(@"using Enjune.Ecs.Component;");
            sb.AppendLine(@"");
            sb.AppendLine(@"namespace Enjune.Ecs.EcsType;");
            sb.AppendLine(@"public partial class QueryBuilder");
            sb.AppendLine(@"{");
            
            // Add all QueryBuilder Retrieve<> versions
            AddQueryBuilderRetrieveSeries(sb);

            sb.AppendLine(@"}");

            source = sb.ToString();
            context.AddSource($"QueryBuilder.g.cs", source);
        }

        public void Initialize(GeneratorInitializationContext context) { }

        public static void AddQueryClass(StringBuilder sb, int arity)
        {
            var typeParams = Enumerable.Range(1, arity).Select(i => $"T{i}").ToArray();
            string typeParamList = string.Join(", ", typeParams);
            string constraints = string.Join(" ", typeParams.Select(t => $"where {t} : struct, IComponent"));
            string deconstructPattern = $"(entities, {string.Join(", ", Enumerable.Range(1, arity).Select(i => $"col{i}"))})";
            string actionArgs = $"entities[i], {string.Join(", ", Enumerable.Range(1, arity).Select(i => $"ref col{i}[i]"))}";
            string cacheType = $"(Entity[] entities, {string.Join(", ", typeParams.Select((t, idx) => $"Column<{t}> Column{idx + 1}"))})";
            string getColumnsExpr = $"(archetype.GetEntities(), {string.Join(", ", typeParams.Select(t => $"archetype.GetColumn<{t}>()"))})";

            // Header and fields
            sb.AppendLine($"public class Query<{typeParamList}>(World world, Signature include, Signature exclude) {constraints}");
            sb.AppendLine(@"{");
            sb.AppendLine(@"    private readonly World _world = world;");
            sb.AppendLine(@"    private readonly Signature _include = include;");
            sb.AppendLine(@"    private readonly Signature _exclude = exclude;");
            sb.AppendLine($"    private static List<{cacheType}> _cache = [];");
            sb.AppendLine(@"    private static int _cacheVersion = -1;");

            // GetCache method
            sb.AppendLine($"    internal List<{cacheType}> GetCache(World world, Signature include, Signature exclude)");
            sb.AppendLine(@"    {");
            sb.AppendLine(@"        if (world.CacheVersion == _cacheVersion) return _cache;");
            sb.AppendLine(@"        _cache.Clear();");
            sb.AppendLine(@"        foreach (var archetype in world.QueryArchetypes(include, exclude))");
            sb.AppendLine(@"        {");
            sb.AppendLine($"            _cache.Add({getColumnsExpr});");
            sb.AppendLine(@"        }");
            sb.AppendLine(@"        _cacheVersion = world.CacheVersion;");
            sb.AppendLine(@"        return _cache;");
            sb.AppendLine(@"    }");

            // ForEach method
            sb.AppendLine($"    public void ForEach(ForEachDelegate<{typeParamList}> action)");
            sb.AppendLine(@"    {");
            sb.AppendLine(@"        var cache = GetCache(_world, _include, _exclude);");
            sb.AppendLine($"        foreach (var {deconstructPattern} in cache)");
            sb.AppendLine(@"        {");
            sb.AppendLine(@"            for (int i = 0; i < col1.Count; i++)");
            sb.AppendLine(@"            {");
            sb.AppendLine($"                action({actionArgs});");
            sb.AppendLine(@"            }");
            sb.AppendLine(@"        }");
            sb.AppendLine(@"    }");

            sb.AppendLine(@"}");
        }

        private static void AddQueryClassSeries(StringBuilder sb)
        {
            for (int arity = MinArity; arity <= MaxArity; arity++) AddQueryClass(sb, arity);
        }

        private static void AddDelegate(StringBuilder sb, int arity)
        {
            var typeParams = Enumerable.Range(1, arity).Select(i => $"T{i}").ToArray();
            string typeParamList = string.Join(", ", typeParams);
            string constraints = string.Join(" ", typeParams.Select(t => $"where {t} : struct, IComponent"));
            string refParams = string.Join(", ", typeParams.Select((t, idx) => $"ref {t} t{idx + 1}"));

            sb.AppendLine($"public delegate void ForEachDelegate<{typeParamList}>(Entity entity, {refParams}) {constraints};");
        }

        private static void AddDelegateSeries(StringBuilder sb)
        {
            for (int arity = MinArity; arity <= MaxArity; arity++) AddDelegate(sb, arity);
        }

        private static void AddQueryBuilderRetrieve(StringBuilder sb, int arity)
        {
            var typeParams = Enumerable.Range(1, arity).Select(i => $"T{i}").ToArray();
            string typeParamList = string.Join(", ", typeParams);
            string constraints = string.Join(" ", typeParams.Select(t => $"where {t} : struct, IComponent"));

            sb.AppendLine($"    public Query<{typeParamList}> Retrieve<{typeParamList}>() {constraints}");
            sb.AppendLine(@"    {");
            foreach (string typeParam in typeParams)
            {
                sb.AppendLine($"        IncludeWith<{typeParam}>();");
            }
            sb.AppendLine($"        return new Query<{typeParamList}>(_world, _includeBuilder.Build(), _excludeBuilder.Build());");
            sb.AppendLine(@"    }");
        }

        private static void AddQueryBuilderRetrieveSeries(StringBuilder sb)
        {
            for (int arity = MinArity; arity <= MaxArity; arity++) AddQueryBuilderRetrieve(sb, arity);
        }
    }
}
