<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="OpenTK.Graphics" Version="4.9.4" />
      <PackageReference Include="OpenTK.Mathematics" Version="4.9.4" />
      <PackageReference Include="OpenTK.Windowing.GraphicsLibraryFramework" Version="4.9.4" />
      <PackageReference Include="StbImageSharp" Version="2.30.15" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="resources\atlas.png" />
      <EmbeddedResource Include="Resources\atlas.png" />
      <None Remove="Resources\OpenGL\frag.frag" />
      <EmbeddedResource Include="Resources\OpenGL\frag.frag" />
      <None Remove="Resources\OpenGL\vert.vert" />
      <EmbeddedResource Include="Resources\OpenGL\vert.vert" />
      <None Remove="Resources\Models\cessna.obj" />
      <EmbeddedResource Include="Resources\Models\cessna.obj" />
    </ItemGroup>

</Project>
